<?php

namespace ntentan\views\helpers;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/views/Helper.php';

/**
 * Test class for Helper.
 * Generated by PHPUnit on 2010-12-17 at 09:02:26.
 */
class HelperTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Helper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Helper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
