<?php

namespace ntentan\views;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/views/Presentation.php';

/**
 * Test class for Presentation.
 * Generated by PHPUnit on 2010-12-17 at 09:02:26.
 */
class PresentationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Presentation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Presentation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
