<?php

require_once 'tests/lib/SqlDatabaseTestCase.php';
require_once 'lib/models/datastores/DataStore.php';
require_once 'lib/models/datastores/SqlDatabase.php';
require_once 'lib/models/datastores/Postgresql.php';

/**
 * Test class for DataStore.
 * Generated by PHPUnit on 2010-12-17 at 09:02:29.
 */
class PostgreSqlTest extends \ntentan\test_cases\SqlDatabaseTestCase
{
    protected function setUp()
    {
        \ntentan\Ntentan::$dbConfigFile = 'tests/config/postgresql_db.php';
        parent::setUp();
    }

    protected function getConnection()
    {
        $pdo = new PDO('pgsql:host=localhost;dbname=ntentan_test', 'postgres', 'hello');
        return $this->createDefaultDBConnection($pdo);//, 'test');
    }
    
    protected function getInstance()
    {
        $parameters['hostname'] = 'localhost';
        $parameters['username'] = 'postgres';
        $parameters['password'] = 'hello';
        $parameters['database'] = 'ntentan_test';
        return new \ntentan\models\datastores\Mysql($parameters);
    }
}
