#!/usr/bin/env php
<?php

define('NTENTAN_HOME', '/home/ekow/Projects/ntentan/');
error_reporting(E_ALL ^ E_NOTICE);

// Check if the ntentan framework has been initialized
if(!file_exists("config/ntentan.php") && $argv[1] != "create" && $argv[2] != "app")
{
    echo 
"
Welcome to the Ntentan Framework!

This directory has either not been initialized with ntentan or it does 
not contain an ntentan application. To intialize this directory with a 
basic ntentan application execute:

    {$argv[0]} create app -i
    
";
    die();
}
else if(!isset($argv[1]))
{
    echo
"
Welcome to the Ntentan Framework!
Please specify an action to perform.
";
    die();

}
else if($argv[1] == 'create')
{
    //
}
else
{
    include "config/ntentan.php";
}

require_once(NTENTAN_HOME . "lib/Ntentan.php");
require_once(NTENTAN_HOME . "utils/Util.php");

$utilClassName = ntentan\Ntentan::camelize($argv[1]);
if($argv[1] != "create" && $argv[2] != "app")
{
    ntentan\Ntentan::boot();
}

include_once("utils/$utilClassName.php");

array_shift($argv);
array_shift($argv);

if(class_exists("ntentan\\utils\\$utilClassName"))
{
    $utilClass = "ntentan\\utils\\$utilClassName";
    $util = new $utilClass($modules_path);
    $util->execute($argv);
}
else
{
    fputs(STDERR, "Sorry the script you requested doesn't exist.\n");
}
