#!/usr/bin/env php
<?php

define('NTENTAN_HOME', '/home/ekow/Projects/ntentan/');

// Check if the ntentan framework has been initialized
if(!file_exists("config/ntentan.php") && $argv[1] != "app" && $argv[2] != "create")
{
    echo 
"
Welcome to the Ntentan Framework!

This directory has either not been initialized with ntentan or it does 
not contain an ntentan application. To intialize this directory with a 
basic ntentan application execute:

    {$argv[0]} app create -i
    
";
    die();
}

require_once("Ntentan.php");
require_once("utils/Util.php");

$utilClassName = ntentan\Ntentan::camelize($argv[1]);
if($argv[1] != "app" && $argv[2] != "create")
{
    ntentan\Ntentan::boot();
}

include_once("utils/$utilClassName.php");

array_shift($argv);
array_shift($argv);

if(class_exists("ntentan\\utils\\$utilClassName"))
{
    $utilClass = "ntentan\\utils\\$utilClassName";
    $util = new $utilClass();
    $util->execute($argv);
    //require_once("utils/$utilClassName.php");
}
else
{
    fputs(STDERR, "Invalid script. Execution function doesn't exist\n");
}

/*if($argv[1] != "app" && $argv[2] != "create")
{
    ntentan\Ntentan::boot();
}

array_shift($argv);
array_shift($argv);
if(function_exists("execute"))
{
    execute($argv);
}
else
{
    fputs(STDERR, "Invalid script. Execution function doesn't exist");
}*/
