<?php
ini_set("include_path", "../lib/toolbar".PATH_SEPARATOR."../../../lib/toolbar".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/home/ekow/Projects/ntentan/lib/toolbar/ToolbarItem.php';

/**
 * Test class for ToolbarItem.
 * Generated by PHPUnit on 2010-08-12 at 08:44:38.
 */
class ToolbarItemTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ToolbarItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ToolbarItem;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
