<?php

namespace ntentan\views\helpers\forms\api\renderers;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../../../lib/views/helpers/forms/api/renderers/Renderer.php';

/**
 * Test class for Renderer.
 * Generated by PHPUnit on 2010-12-17 at 09:02:44.
 */
class RendererTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Renderer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Renderer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
