<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/models/Behaviour.php';

/**
 * Test class for Behaviour.
 * Generated by PHPUnit on 2010-12-17 at 09:02:23.
 */
class BehaviourTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Behaviour
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Behaviour;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
