<?php

namespace ntentan\controllers\components\auth;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../lib/controllers/components/auth/AuthMethod.php';

/**
 * Test class for AuthMethod.
 * Generated by PHPUnit on 2010-12-17 at 09:02:32.
 */
class AuthMethodTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AuthMethod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AuthMethod;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testAuthLocalPassword().
     */
    public function testAuthLocalPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
