<?php

namespace ntentan\controllers;

use \ReflectionClass;
use \ReflectionObject;
use ntentan\Ntentan;
use ntentan\views\View;
use ntentan\models\Model;

/**
 * The Controller class represents the base class for all controllers that are
 * built for the ntentan framework. Controllers are used to direct the flow of
 * your application logic. They are stored in modules and they contain methods 
 * which are called from the url. Parameters to the methods are also passed 
 * through the URL. If a method is not specified, the default method is called.
 * The methods called by the controllers are expected to set data into variables
 * which are later rendered as output to the end user through views.
 *
 * @author James Ekow Abaka Ainooson
 * @todo Controllers must output data that can be passed to some kind of template
 *       engine like smarty.
 * 
 */
class Controller
{
    /**
     * The name of the default method to execute when the controller is called 
     * without any action methods specified.
     * @var string
     */
    public $defaultMethodName = "run";

	/**
	 * A copy of the path that was used to load this controller.
	 * @var String
	 */
	public $path;

	/**
	 * A short machine readable name for this controller.
	 * @var string
	 */
	public $name;

    /**
     * The variables generated by any method called in this controller are
     * stored in this array. The values from this array would later be used
     * with the view classes to render the views.
     * @var Array
     */
    public $variables = array();
    
    /**
     * An array of the names of all the components loaded for use by this 
     * controller.
     * @var array
     */
    protected $components = array();

    /**
     * An array of the instances of the components loaded for use by this
     * controller.
     * @var array
     */
    private $componentInstances = array();

    /**
     * The instance of the view template which is going to be used to render 
     * the output of this controller.
     * @var View
     */
    public $viewInstance;
    
    /**
     * The instance of the model class which shares the same package or namespace
     * with this controller.
     * @var Model
     */
    private $modelInstance;
    
    /**
     * A path to the model of the default model this controller is liked to.
     * @var string
     */
    private $modelPath;
    
    /**
     * The data this controller holds for passing ot to the template.
     * @var array
     */
    public $data;
    
    /**
     * The path to the file of this controller's class.
     * @var unknown_type
     */
    public $filePath;
    
    public $method;
    
    protected $blocks = array();
    
    public function __construct()
    {
        foreach($this->components as $component)
        {
            $this->addComponent($component);
        }
    }

    public function getName()
    {
        $object = new ReflectionObject($this);
        return $object->getName();
    }

    public function __set($property, $value)
    {
        switch($property)
        {
        case "layout":
            $this->view->layout = $value;
            break;
        }
    }

    public function __get($property)
    {
        switch ($property)
        {
        case "view":
            if($this->viewInstance == null)
            {
                $this->viewInstance = new View();
                $this->viewInstance->layout = "main";
                $this->viewInstance->template = $path;
                $this->viewInstance->defaultTemplatePath = $this->filePath;
            }
            return $this->viewInstance;

        case "layout":
            return $this->view->layout;
            
        case "model":
            if($this->modelInstance == null)
            {
                $this->modelInstance = Model::load($this->modelPath);
            }
            return $this->modelInstance;
            
        case "directory":
            return Ntentan::$modulesPath . $this->path . "/";
            
        default:
            if(substr($property, -5) == "Block")
            {
                $block = Ntentan::deCamelize(substr($property, 0, strlen($property) - 5));
                return $this->blocks[$block];
            }
            else if(substr($property, -9) == "Component")
            {
                $component = substr($property, 0, strlen($property) - 9);
                return $this->componentInstances[$component];
            }
        }
    }

    /**
     * Adds a component to the controller.
     * @param string $component Name of the component
     */
    public function addComponent()
    {
        $arguments = func_get_args();
        $component = array_shift($arguments);
        Ntentan::addIncludePath(Ntentan::getFilePath("controllers/components/$component"));
        $componentName = "\\ntentan\\controllers\\components\\$component\\" . ucfirst($component);
        $componentClass = new ReflectionClass($componentName);
        $componentInstance = $componentClass->newInstanceArgs($arguments);
        $componentInstance->filePath = Ntentan::getFilePath("controllers/components/$component");
        $componentInstance->setController($this);
        $componentInstance->init();
        $this->componentInstances[$component] = $componentInstance;
    }

    public function addBlock($blockName, $alias = null)
    {
        $blockFile = "blocks/$blockName/" . Ntentan::camelize($blockName) . ".php";
        if(file_exists($blockFile))
        {
            Ntentan::addIncludePath(Ntentan::$blocksPath . "$blockName");
            $blockClass = "\\" . Ntentan::$modulesPath . "\\blocks\\$blockName\\" . Ntentan::camelize($blockName);
            $path = "blocks/$blockName"; 
        }
        else if(file_exists(Ntentan::getFilePath("views/blocks/$blockName/" . Ntentan::camelize($blockName) . ".php")))
        {
            Ntentan::addIncludePath(Ntentan::getFilePath("views/blocks/$blockName"));
            $blockClass = "\\ntentan\\views\\blocks\\$blockName\\" . Ntentan::camelize($blockName);
            $path = Ntentan::getFilePath("views/blocks/$blockName"); 
        }
        else
        {
            Ntentan::message("Block <code>$blockname</code> not found");
        }
        
        $blockInstance = new $blockClass();
        $blockInstance->setName($blockName);
        $blockInstance->setPath($path);
        if($alias == null) $alias = $blockName;
        $this->blocks[$alias] = $blockInstance;
    }

    /**
     * 
     * @param mixed $params1
     * @param string $params2
     */
    protected function set($params1, $params2 = null)
    {
        if(is_array($params1))
        {
            $this->variables = array_merge($this->variables, $params1);
        }
        else
        {
            $this->variables[$params1] = $params2;
        }
    }
    
    /**
     * Appends a string to an already setup template variable.
     * @param string $params1
     * @param string $params2
     */
    protected function append($params1, $params2)
    {
        $this->variables[$params1] .= $params2;
    }

    protected function get()
    {
        return $this->variables;
    }

	/**
	 * A utility method to load a controller. This method loads the controller
	 * and fetches the contents of the controller into the Controller::$contents
	 * variable if the get_contents parameter is set to true on call. If a
     * controller doesn't exist in the module path, a ModelController is loaded
     * to help manipulate the contents of the model. If no model exists in that
     * location, it is asumed to be a package and a package controller is
     * loaded.
	 *
	 * @param $path 		The path for the model to be loaded.
	 * @return Controller
	 */
	public static function load($path)
	{
        $controllerPath = '';
        $controllerPathArray = explode('/', $path);

        // Filter out all empty paths from the query
        foreach($controllerPathArray as $value)
        {
            if($value == "") continue;
            $pathArray[] = $value;
        }
        
        // Loop through the filtered path and extract the controller class
		for($i = 0; $i<count($pathArray); $i++)
		{
			$p = $pathArray[$i];
            $pCamelized .= Ntentan::camelize($p);
            $filePath = Ntentan::$modulesPath . "$controllerPath/$p/";
			if(file_exists($filePath . "{$pCamelized}Controller.php"))
			{
				$controllerName = $pCamelized."Controller";
				$controllerPath .= "/$p";
                $modelPath .= "$p";
				break;
			}
			else
			{
				$controllerPath .= "/$p";
                $modelPath .= "$p.";
			}
		}

        $controllerPath = substr($controllerPath,1);

        if($controllerName == "")
        {
            Ntentan::error("Path not found! [$path]");
        }
        else
        {
            Ntentan::addIncludePath(Ntentan::$modulesPath . "/$controllerPath/"); //$controllerName.php";
            $controllerNamespace = "\\" . str_replace("/", "\\", Ntentan::$modulesPath . "/$controllerPath/");
            $controllerName = $controllerNamespace . $controllerName;
            if(class_exists($controllerName))
            {
                $controller = new $controllerName();
                $controller->setPath($controllerPath);
                $controller->setName($controllerName);
                $controller->modelPath = $modelPath;
                $controller->filePath = $filePath;
            }
            else
            {
            	Ntentan::error("Controller class <b><code>$controllerName</code></b> not found.");
            }
            if($i != count($pathArray)-1)
            {
                $controller->method = $pathArray[$i+1];
            }
            else
            {
                $controller->method = $controller->defaultMethodName;
            }
            
            $controller->init();
            if($controller->hasMethod())
            {
                $ret = $controller->runMethod(array_slice($pathArray,$i+2));
            }
            else
            {
                echo Ntentan::message("Method not found <code><b>$controllerName::{$controller->method}()</b></code>");
                die();
            }
        }
	}
    
	/**
	 * Set the name of this controller
	 * @param string $name
	 */
    public function setName($name)
    {
        $this->name = $name;
        foreach($this->componentInstances as $component)
        {
            $component->setControllerName($name);
        }
    }

    public function setPath($path)
    {
        $this->path = $path;
        foreach($this->componentInstances as $component)
        {
            $component->setControllerPath($path);
        }
    }

    public function hasMethod($method = null)
    {
        $ret = false;
        $path = $method === null ? $this->method : $method;
        if(method_exists($this, $path))
        {
            $ret = true;
        }
        else
        {
            foreach($this->componentInstances as $component)
            {
                $ret = $component->hasMethod($path);
                if($ret)
                {
                    break;
                }
            }
        }
        return $ret;
    }

    public function setView($view)
    {
        $this->viewInstance = $view;
    }

    public function runMethod($params, $method = null)
    {
        $path = $method === null ? $this->method : $method;
        if(method_exists($this, $path))
        {
            $this->mainPreRender();
            $controllerClass = new ReflectionClass($this->getName());
            $method = $controllerClass->GetMethod($path);
            $this->view->template = Ntentan::$modulesPath . "/$this->path/$path.tpl.php";
            $method->invokeArgs($this, $params);
            $this->view->blocks = $this->blocks;
            $ret = $this->view->out($this->get());
            $this->mainPostRender();
        }
        else
        {
            foreach($this->componentInstances as $component)
            {
                if($component->hasMethod($path))
                {
                    $component->variables = $this->variables;
                    $component->blocks = $this->blocks;
                    $component->runMethod($params, $path);
                }
            }
        }
        echo $ret;
    }

    public function mainPreRender()
    {
        foreach($this->componentInstances as $component)
        {
            $component->preRender();
        }
        $this->preRender();
    }

    public function mainPostRender()
    {
        foreach($this->componentInstances as $component)
        {
            $component->postRender();
        }
        $this->postRender();
    }

    public function preRender()
    {

    }

    public function postRender()
    {
        
    }
    
    public function hasComponent($component)
    {
        if(array_search($component, $this->components) !== false)
        {
            return true;        
        }
        else
        {
            return false;
        }
    }

    /**
     * Function called automatically after the controller is initialized. This
     * method should be overriden by controllers which want to initialize
     * certain variables after the constructor function is called.
     */
    public function init()
    {
        
    }
}
