<?php

namespace ntentan\exceptions;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/exceptions/FileNotFoundException.php';

/**
 * Test class for FileNotFoundException.
 * Generated by PHPUnit on 2010-12-17 at 09:02:25.
 */
class FileNotFoundExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FileNotFoundException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FileNotFoundException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
