<?php
ini_set("include_path", "../controllers/components/auth".PATH_SEPARATOR."../../../../controllers/components/auth".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/home/ekow/Projects/ntentan/controllers/components/auth/AuthMethod.php';

/**
 * Test class for AuthMethod.
 * Generated by PHPUnit on 2010-08-12 at 08:45:09.
 */
class AuthMethodTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AuthMethod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AuthMethod;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetAuthComponent().
     */
    public function testSetAuthComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
