<?php
ini_set("include_path", "../lib/fapi/Forms".PATH_SEPARATOR."../../../../lib/fapi/Forms".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/home/ekow/Projects/ntentan/lib/fapi/Forms/DayHoursField.php';

/**
 * Test class for DayHoursField.
 * Generated by PHPUnit on 2010-08-12 at 08:44:49.
 */
class DayHoursFieldTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DayHoursField
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DayHoursField;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
