<?php
ini_set("include_path", "../lib/rapi".PATH_SEPARATOR."../../../lib/rapi".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/home/ekow/Projects/ntentan/lib/rapi/Report.php';

/**
 * Test class for Report.
 * Generated by PHPUnit on 2010-08-12 at 08:44:36.
 */
class ReportTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Report
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Report;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
