<?php

namespace ntentan\models\exceptions;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../lib/models/exceptions/DataStoreException.php';

/**
 * Test class for DataStoreException.
 * Generated by PHPUnit on 2010-12-17 at 09:02:29.
 */
class DataStoreExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DataStoreException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DataStoreException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
