<?php

namespace ntentan\models\exceptions;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../lib/models/exceptions/MethodNotFoundException.php';

/**
 * Test class for MethodNotFoundException.
 * Generated by PHPUnit on 2010-12-17 at 09:02:30.
 */
class MethodNotFoundExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MethodNotFoundException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MethodNotFoundException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
