<?php

namespace ntentan\utils;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/utils/Janitor.php';

/**
 * Test class for Janitor.
 * Generated by PHPUnit on 2011-01-19 at 04:05:12.
 */
class JanitorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Janitor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Janitor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testCleanHtml().
     */
    public function testCleanHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testUnquote().
     */
    public function testUnquote() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
