o<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/controllers/ControllerMethodNotFoundException.php';

/**
 * Test class for ControllerMethodNotFoundException.
 * Generated by PHPUnit on 2011-01-19 at 04:05:10.
 */
class ControllerMethodNotFoundExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ControllerMethodNotFoundException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ControllerMethodNotFoundException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
