<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace ntentan;

/**
 * Description of View
 *
 * @author ekow
 */
class View 
{
    private static $layout = 'main.tpl.php';
    private static $template;
    private static $cacheTimeout = false;
    
    /**
     * The variables generated by any method called in this controller are
     * stored in this array. The values from this array would later be used
     * with the view classes to render the views.
     * @var Array
     */
    private static $variables = array();

    
    public static function setContentType($contentType)
    {
        header("Content-Type: $contentType");
    }
    
    public static function getCacheTimeout()
    {
        return self::$cacheTimeout;
    }
    
    public static function setCacheTimeout($cacheTimeout)
    {
        self::$cacheTimeout = $cacheTimeout;
    }
    
    public static function setLayout($layout)
    {
        self::$layout = $layout;
    }
    
    public static function getTemplate()
    {
        return self::$template;
    }
    
    public static function setTemplate($template)
    {
        self::$template = $template;
    }
    
    /**
     *
     * @param mixed $params1
     * @param string $params2
     */
    public static function set($params1, $params2 = null)
    {
        if (is_string($params1)) {
            self::$variables[$params1] = $params2;
        } else if (is_array($params1)) {
            self::$variables += $params1;
        }
    }  
    
    public static function out()
    {
        require_once 'view_functions.php';
        $viewData = self::$variables;
        if(self::$template != false)
        {
            $renderedTemplate = honam\TemplateEngine::render(self::$template, $viewData);
            $viewData['contents'] = $renderedTemplate;
        }
        if(self::$layout != FALSE)
        {
            return honam\TemplateEngine::render(self::$layout, $viewData);
        }
    }
}
