<?php

namespace ntentan;

use ntentan\honam\TemplateEngine;
use ntentan\honam\AssetsLoader;

/**
 * Description of View
 *
 * @author ekow
 */
class View {

    private $layout = 'main.tpl.php';
    private $template;
    private $cacheTimeout = false;

    /**
     * The variables generated by any method called in this controller are
     * stored in this array. The values from this array would later be used
     * with the view classes to render the views.
     * @var Array
     */
    private $variables = array();
    
    public function __construct() {
    }

    public function setContentType($contentType) {
        header("Content-Type: $contentType");
    }

    public function getCacheTimeout() {
        return $this->cacheTimeout;
    }

    public function setCacheTimeout($cacheTimeout) {
        $this->cacheTimeout = $cacheTimeout;
    }

    public function setLayout($layout) {
        $this->layout = $layout;
    }

    public function getTemplate() {
        return $this->template;
    }

    public function setTemplate($template) {
        $this->template = $template;
    }

    /**
     *
     * @param mixed $params1
     * @param string $params2
     */
    public function set($params1, $params2 = null) {
        if (is_string($params1)) {
            $this->variables[$params1] = $params2;
        } else if (is_array($params1)) {
            $this->variables += $params1;
        }
    }

    public function __toString() {
        require_once 'view_functions.php';
        $viewData = $this->variables;
        if ($this->template != false) {
            $renderedTemplate = honam\TemplateEngine::render($this->template, $viewData);
            $viewData['contents'] = $renderedTemplate;
        }
        if ($this->layout != FALSE) {
            return honam\TemplateEngine::render($this->layout, $viewData);
        }
    }

}
