<?php
ini_set("include_path", "../lib/models/datastores".PATH_SEPARATOR."../../../../lib/models/datastores".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/home/ekow/Projects/ntentan/lib/models/datastores/DataStore.php';

/**
 * Test class for DataStore.
 * Generated by PHPUnit on 2010-08-12 at 08:44:47.
 */
class DataStoreTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DataStore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataStore;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetKeyField().
     */
    public function testGetKeyField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
