<?php

require_once 'PHPUnit/Framework.php';
require_once 'lib/test_cases/SqlDatabaseTestCase.php';
require_once 'lib/models/datastores/DataStore.php';
require_once 'lib/models/datastores/SqlDatabase.php';
require_once 'lib/models/datastores/Mysql.php';

/**
 * Test class for DataStore.
 * Generated by PHPUnit on 2010-12-17 at 09:02:29.
 */
class MysqlTest extends \ntentan\test_cases\SqlDatabaseTestCase
{
    protected function setUp()
    {
        \ntentan\Ntentan::$dbConfigFile = 'tests/config/mysql_db.php';
        parent::setUp();
    }

    protected function getConnection()
    {
        $pdo = new PDO('mysql:host=localhost;dbname=ntentan_test', 'root', 'root');
        return $this->createDefaultDBConnection($pdo);//, 'test');
    }

    protected function getInstance()
    {
        $parameters['hostname'] = 'localhost';
        $parameters['username'] = 'root';
        $parameters['password'] = 'root';
        $parameters['database'] = 'ntentan_test';
        return new \ntentan\models\datastores\Mysql($parameters);
    }
}
