<?php
namespace ntentan\views\helpers\dates;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../lib/views/Helper.php';
require_once dirname(__FILE__) . '/../../../../../lib/views/helpers/dates/DatesHelper.php';

/**
 * Test class for Helper.
 * Generated by PHPUnit on 2011-01-19 at 04:05:13.
 */
class DatesHelperTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Helper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DatesHelper();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function testFormat()
    {
        $this->assertEquals($this->object->format(), '1st January, 1970');
        $this->assertEquals($this->object->parse('1987-06-11')->format(), '11th June, 1987');
    }

    public function testTime()
    {
        $this->assertEquals('12:00 am', $this->object->time());
        $this->assertEquals('11:12 pm', $this->object->parse('1987-06-11 23:12:36')->time());
    }

    public function testSentence()
    {
        $this->assertEquals('now', $this->object->sentence('2010-01-01', null, '2010-01-01'));
        $this->assertEquals('now', $this->object->sentence('2010-01-01 12:00:00', null, '2010-01-01 12:00:05'));
        $this->assertEquals('13 seconds' , $this->object->sentence('2010-01-01 12:00:00', null, '2010-01-01 12:00:13'));
        $this->assertEquals('30 minutes' , $this->object->sentence('2010-01-01 12:00:00', null, '2010-01-01 12:30:13'));
        $this->assertEquals('1 hour', $this->object->sentence('2010-01-01 12:00:00', null, '2010-01-01 13:30:13'));
        $this->assertEquals('yesterday' , $this->object->sentence('2010-01-01 12:00:00', null, '2010-01-02 13:30:13'));
        $this->assertEquals('2 days' , $this->object->sentence('2010-01-01 12:00:00', null, '2010-01-03 13:30:13'));
        $this->assertEquals('1 week' , $this->object->sentence('2010-01-01 12:00:00', null, '2010-01-08 13:30:13'));
        $this->assertEquals('2 months' , $this->object->sentence('2010-01-01 12:00:00', null, '2010-03-08 13:30:13'));
        $this->assertEquals('1 year' , $this->object->sentence('2010-01-01 12:00:00', null, '2011-03-08 13:30:13'));
        $this->assertEquals('1 year ago' , $this->object->sentence('2010-01-01 12:00:00', array('elaborate_with' => 'ago'), '2011-03-08 13:30:13'));
    }
}
