name: Tests
on: [push]
jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
      - name: Running composer
        run: composer install
      - name: Running php unit tests
        run: vendor/bin/phpunit
